lib/server-manager.ts
hello,
The signature of LanguageServerProcess interface is not following the signature from `child_process` standard library of Node. As a result, many current lsp implementation in atom-ide with this library does not follow the signature. E.g https://github.com/atom-ide-community/ide-python/blob/master/lib/main.js#L51
=> fix: kill and on exit signature match child_process

lib/adapters/autocomplete-adapter.ts, test/adapters/autocomplete-adapter.test.ts
fixes #99 
I can confirm this fixes replacing the trigger character in multiple autocomplete suggestion packages.
I don't know if this is just a bug from https://github.com/atom/atom-languageclient/pull/264 or if there was a reason `triggerPoint` was used. Perhaps @Aerijo might be able to give some insight?
~~I am also having some issues figuring out how to write a test for this.~~ I think I figured it out.
=> fix: fix removing triggerChar

lib/auto-languageclient.ts
Based on  https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize
```ts
/**
* The workspace folders configured in the client when the server starts.
* This property is only available if the client supports workspace folders.
* It can be `null` if the client supports workspace folders but none are
* configured.
*
* @since 3.6.0
*/
workspaceFolders?: WorkspaceFolder[] | null;
```
https://github.com/vuejs/vetur/issues/2561#issuecomment-743719403
=> fix: set workspaceFolders to null when there is no workspace

lib/adapters/autocomplete-adapter.ts, test/adapters/autocomplete-adapter.test.ts
This should work the way it is supposed to. I basically reverted #100 and just removed the trigger char from the `replacementPrefix` and added a test to make sure this continues to work in the future.
fixes #113
=> fix: fix autocomplete prefix

lib/adapters/code-action-adapter.ts, lib/adapters/command-execution-adapter.ts, lib/main.ts, test/adapters/command-execution-adapter.test.ts
Followup to #12 , discussions made there and [there](https://github.com/atom/atom-languageclient/issues/183).
A developer can register a callback that happens when an `executeCommand` is fired for `DoBlaBlaJavaThingyTypeBeat`. If a command was not registered with a callback by the developer - let that `Command` reach the server. Otherwise - fire the callback that was registered by the developer.
This brings package developers full control as to how `Command`s are executed "globally".
i.e - they can register a command and a callback for it, and have parts of their package (like code actions, or other custom areas) call those `Command`s and have them executed just like VSCode does today. But, this will probably be mainly needed/used for code actions, [where the standard isn't explicit with …
=> feat: API for registering custom callbacks for Commands

lib/adapters/autocomplete-adapter.ts, lib/types/autocomplete-extended.ts, package.json, pnpm-lock.yaml, test/adapters/autocomplete-adapter.test.ts, tsconfig.json, typings/atom-ide/index.d.ts
This fixes the type errors when atom-languageclient is used with TypeScript.
With this PR, the following client does not error anymore: 
https://github.com/Pure-D/atomize-d/pull/34
=> fix: fix type errors when atom-languageclient is used with TypeScript

README.md, lib/auto-languageclient.ts, lib/main.ts, lib/server-manager.ts, lib/utils.ts, test/utils.test.ts
This fills the gap for native language servers such as for D, Java, etc, or the executables that are not a JavaScript file such as for Python.
- feat: add functions for spawning a general executable: `AutolanguageClient.spawn`
- allow custom handlers for lsProcess `onSpawnClose`, `onSpawnExit`, `onSpawnError`, `onSpawnDisconnect`
- fix LanguageServerProcess type
=> feat: add functions for spawning a general executable + allow custom handlers for lsProcess + fix LanguageServerProcess type

lib/adapters/notifications-adapter.ts, lib/utils.ts, package.json, pnpm-lock.yaml, typings/atom/index.d.ts
This is still not pretty, but arguably less painful than those `*Ext` declarations.
I can't spend much time now on searching through the TypeScript issue tracker and/or constructing a minimal testcase for the bugreport, but we should at least check if it's been already reported at some point.
=> refactor: clean-up module augments

test/adapters/autocomplete-adapter.test.ts
This refactors the `sinon.stub` code into a function by using `sinon.createSandbox` which allows restoring the stubs right after the function finishes.
=> test: improve autocomplete tests by using a unified getSuggestionsMock

lib/languageclient.ts
Ported https://github.com/atom/atom-languageclient/pull/249 to the new repo.
- added missing `onCustomRequest` method
- renamed `onCustom` to `onCustomNotification`
=> Feature: handling custom requests

lib/adapters/definition-adapter.ts, lib/languageclient.ts
According to https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_definition, the `textDocument/definition` request returns not only `Location[]` but also `LocationLink[]`. May I add support for this?
This is my first experience of TypeScript, so please let me know if I make any mistakes.
=> fix: add `LocationLink` support for definition-adapter

lib/adapters/autocomplete-adapter.ts, test/adapters/autocomplete-adapter.test.ts
Currently, Snippets without `insertText` are not completed (empty strings are inserted).
According to the lsp `CompletionItem` spec, Implementation should fall back to `label`.
This pull request fixes it.
>https://microsoft.github.io/language-server-protocol/specification#textDocument_completion
>A string that should be inserted into a document when selecting this completion. When `falsy` the label is used as the insert text for this item.
=> fix: set the correct fallback for Snippet completion

lib/adapters/code-action-adapter.ts, lib/adapters/code-highlight-adapter.ts, lib/adapters/outline-view-adapter.ts, lib/auto-languageclient.ts, lib/languageclient.ts, package.json, pnpm-lock.yaml, test/adapters/code-action-adapter.test.ts, test/languageclient.test.ts
Some LSP requests lack null checking and are causing errors, so I fixed them.
I made the following changes:
1. Added null check (https://github.com/atom-community/atom-languageclient/commit/e20bba5a4fe06b4f1a24f2063b1a60fcd5da1514)
2. Fixed the type definition (https://github.com/atom-community/atom-languageclient/commit/85cc505a5c9999e4da044996aa49e436d32d017a)
3. Use the vscode-languageserver-protocol package for type definition (https://github.com/atom-community/atom-languageclient/compare/85cc505..d665159)
If you don't need the third change, reverting it will still work.
=> Added null check to some adapters and changed type definition

lib/adapters/apply-edit-adapter.ts, lib/adapters/autocomplete-adapter.ts, package.json, pnpm-lock.yaml
Prettier has a new update that formats the code differently causing some CI errors in #153
=> chore: update devDependencies

lib/adapters/code-action-adapter.ts, lib/adapters/diagnostic-adapter.ts, lib/adapters/linter-push-v2-adapter.ts, lib/convert.ts, lib/languageclient.ts, test/adapters/code-action-adapter.test.ts, test/adapters/diagnostics-adapter-test.ts, test/adapters/linter-push-v2-adapter.test.ts, typings/atom/index.d.ts
- Moves the old atom-ide-diagnostics code to a separate adapter
- Adds initial code actions support for the Linter package -> The packages themselves have not implemented this yet
=> feat: initial code actions backend for Linter service 

lib/auto-languageclient.ts, lib/server-manager.ts, test/auto-languageclient.test.ts
- Moves `determineProjectPath` to `AutoLanguageClient` and passes it down to `ServerManager` in its constructor. (supercedes #11)
- Support for out-of-project files (modified from #156)
- Populate additional paths based on the definitions for such files (modified from #156)
=> feat: support out of the project files

lib/auto-languageclient.ts, lib/server-manager.ts
Requires #160 (only the last commit is related to this PR). It was possible to make this based on master, but then we had to fix some conflicts later
=> feat: allow disabling shutdownGracefully

lib/adapters/autocomplete-adapter.ts, lib/auto-languageclient.ts, lib/convert.ts, lib/types/autocomplete-extended.ts, test/adapters/autocomplete-adapter.test.ts
See https://microsoft.github.io/language-server-protocol/specification#textDocument_completion
```ts
/**
* An optional array of additional text edits that are applied when
* selecting this completion. Edits must not overlap (including the same
* insert position) with the main edit nor with themselves.
*
* Additional text edits should be used to change text unrelated to the
* current cursor position (for example adding an import statement at the
* top of the file if the completion item will insert an unqualified type).
*/
```
=> feat: apply additionalTextEdits after completion

lib/adapters/code-action-adapter.ts, lib/auto-languageclient.ts
=> Add missing code action functions for ide-rust 

lib/convert.ts, test/convert.test.ts
resolve ayame113/atom-ide-deno#74
There is a difference in the conversion process between `Convert.uriToPath` and `Convert.pathToUri`.
|function|(arguments -> retuen value)|
|---|---|
|`uriToPath()`|`https://foo.bar/%40`->`https://foo.bar/%40`<br>`https://foo.bar/%2540`->`https://foo.bar/%2540`|
|`pathToUri()`|`https://foo.bar/%40`->`https://foo.bar/%2540`|
The decoding process of urls other than file: was changed by https://github.com/atom-community/atom-languageclient/commit/6f1e149c052888ff00c26b79be66e7bc7109d84f, but it seems that the encoding process was not changed.
This PR modifies the encoding process for paths other than file: .
=> fix(convert/pathToUri): Improve the encoding of non-alphanumeric paths other than the file protocol
